# Generated by Django 4.2.5 on 2023-09-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('min_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('religion_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('caste_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status_preference', models.CharField(blank=True, max_length=20, null=True)),
                ('education_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
