# Generated by Django 4.2.5 on 2023-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_userlike_approved_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
