# Generated by Django 4.2.5 on 2023-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_userlike_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alcohlic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
    ]
