# Generated by Django 4.2.5 on 2023-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_profile_alcohlic_profile_family_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
