# Generated by Django 4.2.5 on 2023-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_userlike_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
