# Generated by Django 4.2.5 on 2023-09-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_community_state_alter_customuser_email_religion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religion',
            name='community',
        ),
        migrations.AddField(
            model_name='community',
            name='religion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.religion'),
            preserve_default=False,
        ),
    ]
